### ISSUE TITLE
Upgrade to Solidity 0.5.0

### ISSUE THREAD

**Issue by darcius** [rocket-pool/rocketpool#103]
Solidity 0.5.0 is out and brings with it a lot of breaking changes, but some new improvements we can utilise. Upgrading all of RP to 0.5 will be required, add all these changes to a new branch.

Truffle doesn't currently come packaged with it, but it's very easy to add. When in the RP contracts directory, do the following to upgrade (note if you use Truffle globally rather than running it via npm test, you'll need to do this for your global truffle install).

- `cd node_modules/truffle`
- `npm install solc@0.5.0`

Documenation - https://solidity.readthedocs.io/en/v0.5.0/index.html
Breaking Changes - https://solidity.readthedocs.io/en/v0.5.0/050-breaking-changes.html

### Task List

- [x] Upgrade all contracts to 0.5.0
- [x] Investigate optimisations such as ABI Decoder for use in the events system.

**Comment by moles1** [comment]
- External functions with calldata parameters converted to public due to solidity-coverage compatibility issues
- Convert public functions back to external once proper support is implemented in solidity-parser-sc
