### ISSUE TITLE
Subsidise users for lost ETH from bad nodes.

### ISSUE THREAD

**Issue by darcius** [rocket-pool/rocketpool#132]
With the ejection for Casper being 16 ETH, we should subsidise effected users out of the node operators portion. So in that case the node operator would get 0 and the users wouldn't lose any ETH. Much more incentivisation for node operators and a really good backing for RP, that you wouldn't lose any ETH if you stake with us.

So even if a node operator left with 31 ETH, they still lose that out of their portion.

**Comment by moles1** [comment]
Implemented on the `subsidise-penalties` branch but requires unit tests to check final withdrawn balances for users & node operator

**Comment by moles1** [comment]
Unit tests implemented
