### ISSUE TITLE
Old Contract Settings

### ISSUE THREAD

**Issue by darcius** [rocket-pool/rocketpool#145]
There's a bunch of old settings in the contract settings files left over from RP1 that aren't used anymore and some new ones which aren't either due to design choices. Best to do a find/remove on those which are redundant now and clean those files up.

eg 

Minipool Settings
`setStakingWithdrawalFeePerc(0.0025 ether);                                      // The staking withdrawal fee given as a % of 1 Ether (eg 0.25%)`

**Comment by moles1** [comment]
As discussed, deposit "staking withdrawal" methods should stay until this logic is completely removed
