### ISSUE TITLE
Storage contracts accessible by older contracts

### ISSUE THREAD

**Issue by epiccoolguy** [rocket-pool/rocketpool#164]
I think this require statement only tests that the calling contract's address was set, but there doesn't seem to be any logic to prevent older contracts from accessing the storage, despite the modifier being called "onlyLatestRocketNetworkContract". Is this how the eternal storage pattern is supposed to work?

https://github.com/rocket-pool/rocketpool/blob/4bb48f4cc889a531bd23696d647d8a1abadd39d9/contracts/RocketStorage.sol#L26

**Comment by gorgos** [comment]
@epiccoolguy Old addresses are deleted in the upgrade:

https://github.com/rocket-pool/rocketpool/blob/b50d72734a343540cec7de63228ef5f1f57ef38c/contracts/RocketUpgrade.sol#L113

**Comment by moles1** [comment]
Apologies for the late reply all!

@epiccoolguy , @gorgos is correct, old contract addresses are removed from storage whenever an upgrade is made, therefore old network contracts are unable to communicate with the rest of the RP network :)
