### ISSUE TITLE
fails with node v12

### ISSUE THREAD

**Issue by SvenMeyer** [rocket-pool/rocketpool#171]
because truffle does not work on node v12 the rocketpool test fails as well
[https://github.com/trufflesuite/truffle/issues/2070](https://github.com/trufflesuite/truffle/issues/2070)
No problems with node v10, so it might be a good idea to mention that.

**Comment by moles1** [comment]
Hi @SvenMeyer , thanks for bringing this to our attention!
We're just in the process of updating our dependencies for node 12+ compatibility now.
Unfortunately this involves switching to a newer release of web3, which has many breaking changes, so this may take some time. We'll keep this issue updated as we go :)

**Comment by moles1** [comment]
Dependencies have been updated to be compatible with node 12+, these tests should run correctly now!
