### ISSUE TITLE
Error: while migrating Migrations: Returned error: Exceeds block gas limit

### ISSUE THREAD

**Issue by SvenMeyer** [rocket-pool/rocketpool#172]
OS : Ubuntu Mate 20.04 (daily 09 Apr 2020)
Truffle v5.1.20 (core: 5.1.20)
Solidity - 0.5.8 (solc-js)
Node v10.20.0
Web3.js v1.2.1

```
$ npm install && npm test
...

Compiling beacon-chain-simulator/contracts/Withdraw.sol...
Error: while migrating Migrations: Returned error: Exceeds block gas limit
    at /home/sum/rocketpool/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.1 (core: 5.0.1)
Node v10.20.0
npm ERR! Test failed.  See above for more details.
```

**Comment by moles1** [comment]
This sounds like a problem with ganache-cli, I'm not sure exactly why you're seeing this behaviour but since we are currently updating dependencies (https://github.com/rocket-pool/rocketpool/issues/171) we'll leave this open until after that's complete and see if you still have the same issue then.

**Comment by moles1** [comment]
@SvenMeyer RP dependencies have been updated, let us know if you're still seeing this error after pulling master and a fresh `npm install`
