### ISSUE TITLE
Update Solidity Version

### ISSUE THREAD

**Issue by darcius** [rocket-pool/rocketpool#173]
There's been a few decent releases of Solidity in the last few months. We'll need to upgrade the contracts to at least the latest base version of 0.6.*. Adding this issue as a reminder in our milestones for the next beta release.

**Comment by Alko89** [comment]
I have been looking into this and am mostly finished. I'm getting warnings for having fallback function without receive and have to research a bit how to implement them both. In 0.6 the fallback has ben split into these two functions.

**Comment by moles1** [comment]
Closing due to upcoming RP contract rework
