### ISSUE TITLE
Error: while migrating Migrations: Returned error: Exceeds block gas limit

### ISSUE THREAD

**Issue by haydenyoung** [rocket-pool/rocketpool#177]
Hi, received this today after blowing away old rocketpool local repo and cloning again.

`npm install && npm test`

**Comment by moles1** [comment]
Hi @haydenyoung, I was unable to reproduce this issue. This could be happening if you already have an ethereum client (or ganache-cli instance) running locally; the test script will try to deploy RP on the existing client. Please check to see if you have anything running on port 8545.

If this is not the case, could you paste your nodejs version info (`node --version`)?
