### ISSUE TITLE
Unable to withdraw nETH

### ISSUE THREAD

**Issue by sobertram** [rocket-pool/rocketpool#188]
Trying to withdraw nETH from an exited minipool isn't working. Looking for confirmation if this is a bug or something else I need to do to achieve this?

Checking status:
**rocketpool minipool s**
**1 Withdrawable minipool(s):**

-----------------

Address:           0xE1b36c4A9D55B18Cf92008a82cAe99349E25dD9F
Status updated:    **2020-12-14, 20:43 +0000 UTC**
Node fee:          10.218161%
Node deposit:      16.000000 ETH
Final balance:     32.042961 ETH

1 minipools are ready for withdrawal:
- 0xE1b36c4A9D55B18Cf92008a82cAe99349E25dD9F (**16.023675 nETH to claim**)

My attempt to withdraw balance:
**rocketpool minipool w**

Please select a minipool to withdraw from:
1: All available minipools
2: 0xE1b36c4A9D55B18Cf92008a82cAe99349E25dD9F (**16.023675 nETH to claim**)
2

**Could not withdraw from minipool 0xE1b36c4A9D55B18Cf92008a82cAe99349E25dD9F: Could not close minipool: Could not close minipool 0xE1b36c4A9D55B18Cf92008a82cAe99349E25dD9F: failed to estimate gas needed: execution reverted: The minipool can only be closed while dissolved.**

So i tried dissolve and returned with message "No minipools can be dissolved."

Thx

**Comment by moles1** [comment]
Yes, this was a bug in the smartnode repo, apologies! A fix has been merged in and will be included in the next release :)
