### ISSUE TITLE
Node withdrawal address can be modified by the hot wallet at any time.

### ISSUE THREAD

**Issue by Tristannn1337** [rocket-pool/rocketpool#194]
In relation to https://github.com/rocket-pool/rocketpool/issues/184 and https://github.com/rocket-pool/smartnode/issues/83

Since the intent of a withdrawal address is to separate the hot wallet used by the node from the wallet that receives staked funds upon exiting, RocketNodeManager.setWithdrawalAddress appears to fail in satisfying that intent as a compromised hot wallet would be able to change the withdrawal address at any time.

One solution would be to remove the setWithdrawalAddress method in favor of a permanent withdrawal address provided upon node registration. 

However, it's also pretty clear that there are some significant inconveniences associated with this approach given the responsibilities and mechanics surrounding the DAOs and RPL. I wonder how difficult it would be for the smart node to offer the option of using WalletConnect for all node-related activities, reducing the hot wallet responsibilities down to maybe only satisfying the requirements of the validator client? If this was possible, Argent or a similar smart-contract-based wallet could be used. With proper configuration, an Argent wallet should have security on par with any other options out there while still being convenient for node management.

**Comment by Raekye** [comment]
There was a discussion on Discord a few days ago. [Here](https://github.com/rocket-pool/rocketpool/blob/3f2c08951f27aff7e4e7c11cfd199f39209bd2cd/contracts/contract/node/RocketNodeManager.sol#L85) is the current/new code. Basically, the withdrawal address can only be updated by the **current** withdrawal address. So you could set it at the beginning (presumably from the node address) to some address from cold storage, and then only by sending a transaction from your cold storage wallet would you be able to change it to something else. Great work by the devs!

**Comment by kanewallmann** [comment]
Correct. Closing this issue as it's no longer relevant with the change mentioned by @Raekye.
