### ISSUE TITLE
SIGSEGV in rocketpool pdao status

### ISSUE THREAD

**Issue by temptrompete** [rocket-pool/rocketpool#303]
$ rocketpool pdao status
The node 0xXXX has NOT been initialized for onchain voting. You need to run `rocketpool pdao initialize-voting` to participate in onchain votes.
The node doesn't have a delegate, which means it can vote directly on onchain proposals after it initializes voting.
The node's local voting power: 0.0000000000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xXXX]

goroutine 1 [running]:
math/big.(*Int).BitLen(...)
	/usr/local/go/src/math/big/int.go:550
math/big.(*Float).SetInt(0xXXX?, 0xXXX?)
	/usr/local/go/src/math/big/float.go:604 +0x12
github.com/rocket-pool/rocketpool-go/utils/eth.WeiToEth(0xXXX?)
	/go/pkg/mod/github.com/rocket-pool/rocketpool-go@v1.8.3-0.20240618173422-783b8668f5b4/utils/eth/units.go:18 +0x4b
github.com/rocket-pool/smartnode/rocketpool-cli/pdao.getStatus(0xXXX?)
	/smartnode/rocketpool-cli/pdao/status.go:123 +0xbc5
github.com/rocket-pool/smartnode/rocketpool-cli/pdao.RegisterCommands.func1(0xXXX?)
	/smartnode/rocketpool-cli/pdao/commands.go:39 +0x13
github.com/urfave/cli.HandleAction({0xXXX?, 0xXXX?}, 0x6?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.12/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0xXXX, 0x6}, {0x0, 0x0}, {0xXXX, 0x1, 0x1}, {0xXXX, 0x13}, {0xXXX, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.12/command.go:175 +0x63e
github.com/urfave/cli.(*App).RunAsSubcommand(0xXXX, 0xXXX)
	/go/pkg/mod/github.com/urfave/cli@v1.22.12/app.go:405 +0xe07
github.com/urfave/cli.Command.startApp({{0xXXX, 0x4}, {0x0, 0x0}, {0xXXX, 0x1, 0x1}, {0xXXX, 0x23}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.12/command.go:380 +0xb58
github.com/urfave/cli.Command.Run({{0xXXX, 0x4}, {0x0, 0x0}, {0xXXX, 0x1, 0x1}, {0xXXX, 0x23}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.12/command.go:103 +0x7e5
github.com/urfave/cli.(*App).Run(0xXXX, {0xXXX, 0x3, 0x3})
	/go/pkg/mod/github.com/urfave/cli@v1.22.12/app.go:277 +0xb27
main.main()
	/smartnode/rocketpool-cli/rocketpool-cli.go:148 +0xe65

$ rocketpool pdao initialize-voting

Would you like to specify a delegate that can vote on your behalf on Protocol DAO proposals?? [y/n]
y

Please enter the delegate's address:
0xXXX

error calling get-voting-initialized: Invalid node

$ rocketpool service version

Your Smart Node is currently using the Ethereum Mainnet.

Rocket Pool client version: 1.13.6
Rocket Pool service version: 1.13.6
Selected Eth 1.0 client: Geth (Locally managed)
	Image: ethereum/client-go:v1.14.5
Selected Eth 2.0 client: Lighthouse (Locally managed)
	Image: sigp/lighthouse:v5.2.0
MEV-Boost client: Enabled (Local Mode)
	Image: flashbots/mev-boost:1.7

**Comment by 0xfornax** [comment]
This issue was fixed on v1.13.7. Thanks for reporting!
