### ISSUE TITLE
Rocket Upgrade - Add New Contract

### ISSUE THREAD

**Issue by darcius** [rocket-pool/rocketpool#32]
We'll need the ability for the owner to add new contracts to Rocket Pool as well as upgrading existing ones. This can be added to the Rocket Upgrade contract.

- [x] Allow owner to add new contract address to storage, verify its name/address isn't currently registered.
- [x] Unit tests to verify contract is registered successfully by the owner. Non owners can't add new contracts etc.

**Comment by mryellow** [comment]
> verify its name/*address* isn't currently registered

Checking over my implementation again and I deviated here a little bit.

There is a case for leaving open the ability to create a new contract name, with an address which is already assigned under another name. Say to migrate naming schema without redeploying contracts.

```
function createContract(string _name, address _newAddress) onlyOwner canInitalise external {
    require(_newAddress != address(0));
    address oldAddress = coreRegistry.getAddress(keccak256("contract.name", _name));
    require(oldAddress == address(0));

    coreRegistry.setAddress(keccak256("contract.name", _name), _newAddress);
    coreRegistry.setAddress(keccak256("contract.address", _newAddress), _newAddress);

    emit ContractCreated(_newAddress, now);
}
```

https://github.com/rocket-pool/rocketpool/pull/34/files#diff-3b7cc10a0894665220480148e2e3182dR88

**Comment by darcius** [comment]
Good stuff guys, I'll close this now :)
