### ISSUE TITLE
Promise style

### ISSUE THREAD

**Issue by mryellow** [rocket-pool/rocketpool#38]
I believe these promises in migrations can be made a little less deeply nested.

 ```
       // Deploy Rocket Vault
        return deployer.deploy(rocketVault, rocketStorage.address).then(() => {
        // Deploy Rocket Vault Store
        return deployer.deploy(rocketVaultStore, rocketStorage.address).then(() => {
          // Deploy Rocket Utils
          return deployer.deploy(rocketUtils, rocketStorage.address).then(() => {
```

```

....then(() => {
  // Deploy Rocket Vault
  return deployer.deploy(rocketVault, rocketStorage.address);
}).then(() => {
  // Deploy Rocket Vault Store
  return deployer.deploy(rocketVaultStore, rocketStorage.address);
}).then(() => {
  // Deploy Rocket Vault Store
  return deployer.deploy(rocketVaultStore, rocketStorage.address);
}).then(() => {
  // Deploy Rocket Utils
  return deployer.deploy(rocketUtils, rocketStorage.address);
}).then(() => {
  ...
})

```

https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

**Comment by darcius** [comment]
Hey @mryellow, appreciate the feedback! This callback hell has been an issue due to Truffle for a while now, but @moles1 has recently made some changes as can be seen here which will be merged soon https://github.com/rocket-pool/rocketpool/pull/35

Would that resolve your issue?

**Comment by mryellow** [comment]
Oh now that is an interesting pattern with the arrays!

Yeah just driving by when I saw the nesting and thought I'd drop that article, found it handy myself.
