### ISSUE TITLE
Casper Integration - Warm-up Period Check

### ISSUE THREAD

**Issue by darrenlangley** [rocket-pool/rocketpool#52]
Casper now includes a warm-up period - we can deposit but should not be voting during the warm-up period.

- pull latest Casper
- make sure tests still work
- implement START_EPOCH in can vote

**Comment by moles1** [comment]
- Removed casper "epoch is current" test - current_epoch is now initialised to a future epoch to account for the warmup period
- Added test for attempting to vote during warmup period
- No contract code updates required - the warmup period is implicitly checked for in "isLoggedIntoCasper" (no validators can possibly be logged in during warmup period)
