### ISSUE TITLE
Solidity Code Coverage

### ISSUE THREAD

**Issue by darcius** [rocket-pool/rocketpool#99]
Need to add in proper code coverage along side our extensive unit tests and into Travis. Using `solidity-coverage` is our best bet imo https://github.com/sc-forks/solidity-coverage

I've added this as a new test script that can be run as `npm run test-cov`. It currently works for me, but produces some odd erros near the end, might just be my WSL env though.

Objectives:

- [x] Get `test-cov` script running successfully.
- [ ] Get coverage > 95% in all current tests, higher the better obv. This could be a sizeable job.
- [ ] Get implement into Travis.

**Comment by moles1** [comment]
Tests required to increase coverage:

- [ ] RocketAdmin.sol - setNodeTrusted method
- [ ] RocketNode.sol - getRandomAvailableNode method - add test cases where only trusted nodes are available, and where no nodes are available
- [ ] RocketPool.sol - getPoolExists method
- [ ] RocketRole.sol - transferOwnership, adminRoleRemove methods

Other steps to increase coverage:

- [ ] RocketAdmin.sol - deploy contract
- [ ] RocketBase.sol - onlyOwner & onlyAdmin modifiers unused - possibly remove these
- [ ] RocketStorage.sol - various get / set / delete methods unused - possibly remove these

**Comment by moles1** [comment]
- [] Add minipool sets unit tests
